apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mm-kafkaclient
  namespace: kafka
spec:
  replicas: 1
  serviceName: kafkaclient
  selector:
    matchLabels:
      app: kafkaclient
  template:
    metadata:
      labels:
        app: kafkaclient
    spec:
      containers:
      - name: kafka
        image: solsson/kafka:0.11.0.0
        command:
        - sh
        - -c
        - exec tail -f /dev/null
        env:
        - name: CA_CRT1
          valueFrom:
            secretKeyRef:
              name: kcluster-cluster-ca-cert
              key: ca.crt
        - name: CA_CRT2
          valueFrom:
            secretKeyRef:
              name: mirrormaker-cluster-ca-cert
              key: ca.crt
        - name: USER_CRT
          valueFrom:
            secretKeyRef:
              name: mirror-maker-user
              key: user.crt
        - name: USER_KEY
          valueFrom:
            secretKeyRef:
              name: mirror-maker-user
              key: user.key